using System;
using System.Collections.Generic;
using System.Linq;
using System.Reactive.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using SLSKDONET.Data.Entities;
using SLSKDONET.Models;
using SLSKDONET.Services;
using SLSKDONET.ViewModels;
using Xunit;

namespace SLSKDONET.Tests.ViewModels;

public class TrackCueEditorViewModelTests
{
    // 120 BPM: beat 0.5 s, bar 2 s, 8-bar phrase 16 s. Downbeat at 1 s.
    private const double Bpm = 120, Downbeat = 1.0, Duration = 300;

    private static (TrackCueEditorViewModel Editor, Mock<ICuePointService> Service) Build(params CuePointEntity[] stored)
    {
        var service = new Mock<ICuePointService>();
        var editor = new TrackCueEditorViewModel("Outgoing", service.Object, null, NullLogger.Instance);
        editor.Load("hash", "Track", null, Bpm, Downbeat, Duration, stored);
        return (editor, service);
    }

    private static CuePointEntity Stored(double t, string label, int slot = -1, CuePointType type = CuePointType.Drop) => new()
    {
        TrackUniqueHash = "hash", TimestampInSeconds = t, Label = label, SlotIndex = slot, Type = type,
        IsAutoGenerated = true, Color = "#FF0000", Confidence = 0.9f,
    };

    [Fact]
    public void Snap_UsesTheTracksGrid_FromTheDownbeat()
    {
        var (editor, _) = Build();

        editor.SnapMode = CueSnapMode.Bar;
        Assert.Equal(5.0, editor.Snap(5.6), 6);   // bars at 1, 3, 5, 7...

        editor.SnapMode = CueSnapMode.Beat;
        Assert.Equal(5.5, editor.Snap(5.6), 6);

        editor.SnapMode = CueSnapMode.Phrase;
        Assert.Equal(17.0, editor.Snap(20.0), 6); // phrases at 1, 17, 33...

        editor.SnapMode = CueSnapMode.Off;
        Assert.Equal(5.6, editor.Snap(5.6), 6);
    }

    [Fact]
    public void AddCue_SnapsTakesTheFirstFreePad_AndMarksDirty()
    {
        var (editor, _) = Build(Stored(10, "Drop", slot: 0));

        editor.AddCueAtCommand.Execute(20.4).Subscribe();

        var added = Assert.Single(editor.Cues, c => c.Name == "Cue 2");
        Assert.Equal(21.0, added.Timestamp, 6);
        Assert.Equal(1, added.SlotIndex); // pad A is taken
        Assert.Equal(CueSource.User, added.Source);
        Assert.Same(added, editor.SelectedCue);
        Assert.True(editor.IsDirty);
    }

    [Fact]
    public void AssigningATakenPad_TurnsItsPreviousOwnerIntoAMemoryCue()
    {
        var (editor, _) = Build(Stored(10, "A", slot: 0), Stored(20, "B", slot: 1));
        editor.SelectedCue = editor.Cues.Single(c => c.Name == "B");

        editor.SelectedSlot = TrackCueEditorViewModel.SlotOptions.Single(o => o.Index == 0);

        Assert.Equal(0, editor.Cues.Single(c => c.Name == "B").SlotIndex);
        Assert.Equal(-1, editor.Cues.Single(c => c.Name == "A").SlotIndex);
    }

    [Fact]
    public void ChangingRole_AppliesItsColour_AndMakesItAUserCue()
    {
        var (editor, _) = Build(Stored(10, "X"));
        editor.SelectedCue = editor.Cues[0];

        editor.SelectedRole = CueRole.Intro;

        Assert.Equal(CueRole.Intro, editor.Cues[0].Role);
        Assert.Equal(CueForgeViewModel.RekordboxColorForRole(CueRole.Intro), editor.Cues[0].Color);
        Assert.Equal(CueSource.User, editor.Cues[0].Source);
    }

    [Fact]
    public void Undo_And_Redo_RestoreEarlierStates()
    {
        var (editor, _) = Build(Stored(10, "Drop"));
        editor.SelectedCue = editor.Cues[0];
        editor.DeleteSelectedCommand.Execute().Subscribe();
        Assert.Empty(editor.Cues);

        editor.UndoCommand.Execute().Subscribe();
        Assert.Single(editor.Cues);
        Assert.Equal("Drop", editor.Cues[0].Name);

        editor.RedoCommand.Execute().Subscribe();
        Assert.Empty(editor.Cues);
    }

    [Fact]
    public void DraggingACue_SnapsIt_AndReportsTheMove()
    {
        var (editor, _) = Build(Stored(11, "Drop"));
        (double From, double To)? moved = null;
        editor.CueMoved += (_, m) => moved = m;

        var cue = editor.Cues[0];
        cue.Timestamp = 14.3; // what the waveform does while dragging
        editor.CueUpdatedCommand.Execute(cue).Subscribe();

        Assert.Equal(15.0, cue.Timestamp, 6);
        Assert.Equal((11.0, 15.0), moved);
        Assert.True(editor.IsDirty);

        editor.UndoCommand.Execute().Subscribe();
        Assert.Equal(11.0, editor.Cues[0].Timestamp, 6);
    }

    [Fact]
    public void NudgingALoop_MovesItsEndToo()
    {
        var (editor, _) = Build(Stored(11, "Drop"));
        editor.SelectedCue = editor.Cues[0];
        editor.SetSelectedLoopBarsCommand.Execute(4).Subscribe();
        Assert.True(editor.Cues[0].IsLoop);
        Assert.Equal(19.0, editor.Cues[0].LoopEndSeconds, 6); // 4 bars = 8 s

        editor.NudgeSelectedCommand.Execute("+bar").Subscribe();

        Assert.Equal(13.0, editor.Cues[0].Timestamp, 6);
        Assert.Equal(21.0, editor.Cues[0].LoopEndSeconds, 6);
    }

    [Fact]
    public async Task Save_ReplacesTheTracksCues_WithTheWorkingSet()
    {
        var (editor, service) = Build(Stored(10, "Drop", slot: 0));
        List<CuePointEntity>? written = null;
        service.Setup(s => s.CreateManyAsync(It.IsAny<IEnumerable<CuePointEntity>>(), It.IsAny<CancellationToken>()))
               .Callback<IEnumerable<CuePointEntity>, CancellationToken>((e, _) => written = e.ToList())
               .Returns(Task.CompletedTask);
        editor.SelectedCue = editor.Cues[0];
        editor.SelectedName = "Big drop";

        Assert.True(await editor.SaveIfDirtyAsync());

        service.Verify(s => s.DeleteAllByTrackIdAsync("hash", It.IsAny<CancellationToken>()), Times.Once);
        var cue = Assert.Single(written!);
        Assert.Equal("Big drop", cue.Label);
        Assert.False(cue.IsAutoGenerated); // edited, so auto-analysis won't overwrite it
        Assert.Equal(0, cue.SlotIndex);
        Assert.False(editor.IsDirty);
        Assert.False(await editor.SaveIfDirtyAsync()); // nothing left to save
    }

    [Fact]
    public void SettingADrop_PlacesCountdowns_MovingItMovesThem_DeletingItRemovesThem()
    {
        var (editor, _) = Build(Stored(81, "Hit", type: CuePointType.PhraseBoundary)); // 120 BPM: bar = 2 s
        editor.InitDropCountdownMode("16,8");
        editor.SelectedCue = editor.Cues.Single();

        editor.SelectedRole = CueRole.Drop;
        Assert.Equal(new[] { 49.0, 65.0, 81.0 }, editor.Cues.Select(c => c.Timestamp));

        editor.NudgeSelectedCommand.Execute("+bar").Subscribe();
        Assert.Equal(new[] { 51.0, 67.0, 83.0 }, editor.Cues.Select(c => c.Timestamp));

        editor.DeleteSelectedCommand.Execute().Subscribe();
        Assert.Empty(editor.Cues);
    }

    [Fact]
    public void CountdownsOff_LeavesTheOtherCuesAlone()
    {
        var (editor, _) = Build(Stored(81, "Hit", type: CuePointType.PhraseBoundary));
        editor.InitDropCountdownMode("Off");
        editor.SelectedCue = editor.Cues.Single();

        editor.SelectedRole = CueRole.Drop;

        Assert.Single(editor.Cues);
    }

    [Fact]
    public void FineNudge_Moves10Ms_WithoutSnapping()
    {
        var (editor, _) = Build(Stored(11, "Drop"));
        editor.SelectedCue = editor.Cues[0];

        editor.NudgeSelectedCommand.Execute("+fine").Subscribe();

        Assert.Equal(11.010, editor.Cues.Single(c => c.Name == "Drop").Timestamp, 6);
    }

    [Fact]
    public void UseAsMixPoint_ReportsTheSelectedCuesTime()
    {
        var (editor, _) = Build(Stored(42, "Outro", type: CuePointType.Outro));
        double? trigger = null;
        editor.TriggerRequested += (_, t) => trigger = t;
        editor.SelectedCue = editor.Cues[0];

        editor.UseSelectedAsTriggerCommand.Execute().Subscribe();

        Assert.Equal(42.0, trigger);
    }
}
