using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SLSKDONET.Data;
using SLSKDONET.Data.Entities;
using SLSKDONET.Engine.Analysis;
using SLSKDONET.Engine.Snapping;

namespace SLSKDONET.Engine.Cueing;

/// <summary>
/// Generates and persists the 8 standard structural DJ cues for a track,
/// performing vocal density checks and phrase-snapping.
/// </summary>
public sealed class CueGenerationService
{
    private readonly IDbContextFactory<AppDbContext> _contextFactory;
    private readonly TransientAwareSnappingEngine _snappingEngine;
    private readonly IntentClassifier _classifier;

    public CueGenerationService(
        IDbContextFactory<AppDbContext> contextFactory)
    {
        _contextFactory = contextFactory ?? throw new ArgumentNullException(nameof(contextFactory));
        _snappingEngine = new TransientAwareSnappingEngine();
        _classifier = new IntentClassifier();
    }

    /// <summary>
    /// Generates the standard 8 cues for a track and saves them to the database.
    /// </summary>
    public async Task<List<CuePointEntity>> GenerateAndPersistCuesAsync(
        string trackHash,
        AnalysisPipelineResult analysis,
        double downbeatAnchor,
        double? vocalStart = null,
        double? vocalEnd = null,
        double? vocalIntensity = null,
        CancellationToken ct = default)
    {
        var cues = GenerateCues(trackHash, analysis, downbeatAnchor, vocalStart, vocalEnd, vocalIntensity);

        using var db = await _contextFactory.CreateDbContextAsync(ct);
        
        // Remove existing auto-generated cues for this track
        var existing = await db.CuePoints
            .Where(c => c.TrackUniqueHash == trackHash && c.IsAutoGenerated)
            .ToListAsync(ct);
        
        db.CuePoints.RemoveRange(existing);
        await db.CuePoints.AddRangeAsync(cues, ct);
        await db.SaveChangesAsync(ct);

        return cues;
    }

    /// <summary>
    /// Generates the standard 8 cues in memory.
    /// </summary>
    public List<CuePointEntity> GenerateCues(
        string trackHash,
        AnalysisPipelineResult analysis,
        double downbeatAnchor,
        double? vocalStart = null,
        double? vocalEnd = null,
        double? vocalIntensity = null)
    {
        var cues = new List<CuePointEntity>();
        double duration = analysis.DurationSeconds;
        double bpm = analysis.Bpm;

        if (duration <= 0 || bpm <= 0) return cues;

        double beatDuration = 60.0 / bpm;
        double barDuration = beatDuration * 4;

        // 1. Build candidate timestamps from all signal sources
        var rawCandidates = new HashSet<double>();

        // Transients (phrase-snapped)
        foreach (var t in analysis.Transients)
        {
            double snapped = _snappingEngine.SnapRawTimeToPhraseLedger(t.Timestamp, bpm, downbeatAnchor);

            // Vocal avoidance: shift cues landing in high-intensity vocal phrases to phrase boundary
            if (vocalStart.HasValue && vocalEnd.HasValue && vocalIntensity.HasValue && vocalIntensity.Value > 0.4
                && snapped >= vocalStart.Value && snapped <= vocalEnd.Value)
            {
                double relativeToPhrase = (snapped - downbeatAnchor) / (beatDuration * 32);
                if (Math.Abs(relativeToPhrase - Math.Round(relativeToPhrase)) > 0.05)
                    snapped = _snappingEngine.SnapRawTimeToPhraseLedger(snapped, bpm, downbeatAnchor);
            }

            rawCandidates.Add(snapped);
        }

        // Sub-bass return timestamps are the highest-confidence drop candidates for DnB
        foreach (var r in analysis.SubBassReturnTimestamps)
            rawCandidates.Add(_snappingEngine.SnapRawTimeToPhraseLedger(r, bpm, downbeatAnchor));

        // Spectral flux novelty drop signatures
        foreach (var (dropTs, _, _) in analysis.NoveltyDropSignatures)
            rawCandidates.Add(_snappingEngine.SnapRawTimeToPhraseLedger(dropTs, bpm, downbeatAnchor));

        // 2. Classify all candidates using the multi-feature weighted classifier
        var classified = _classifier.ClassifyAll(rawCandidates, duration, analysis);
        var candidates = classified
            .Select(c => (Time: c.Timestamp, Intent: c.Result.Intent, Confidence: c.Result.Confidence))
            .ToList();

        // 2. Build the 8 Standard Cues using candidates and mathematical backups

        // Cue 1: First Downbeat
        double downbeatTime = downbeatAnchor;
        cues.Add(CreateCueEntity(trackHash, downbeatTime, CuePointType.Intro, "First Downbeat", 1.0f));

        // Cue 2: Mix-In
        var mixInCand = candidates.FirstOrDefault(c => c.Intent == CueIntent.MixIn);
        double mixInTime = mixInCand.Time != 0 ? mixInCand.Time : downbeatAnchor + (32 * beatDuration); // 8 bars fallback
        cues.Add(CreateCueEntity(trackHash, mixInTime, CuePointType.Intro, "Mix-In", mixInCand.Time != 0 ? mixInCand.Confidence : 0.7f));

        // Cue 4: First Drop
        var drop1Cand = candidates.FirstOrDefault(c => c.Intent == CueIntent.FirstDrop || c.Intent == CueIntent.FirstDrop);
        double drop1Time = drop1Cand.Time != 0 ? drop1Cand.Time : downbeatAnchor + (64 * beatDuration); // 16 bars fallback
        cues.Add(CreateCueEntity(trackHash, drop1Time, CuePointType.Drop, "First Drop", drop1Cand.Time != 0 ? drop1Cand.Confidence : 0.7f));

        // Cue 3: First Breakdown (should be placed before First Drop or after depending on structure)
        var brk1Cand = candidates.FirstOrDefault(c => c.Intent == CueIntent.FirstBreakdown && c.Time < drop1Time);
        double brk1Time = brk1Cand.Time != 0 ? brk1Cand.Time : drop1Time - (32 * beatDuration); // 8 bars before drop fallback
        if (brk1Time <= mixInTime) brk1Time = drop1Time - (16 * beatDuration);
        cues.Add(CreateCueEntity(trackHash, brk1Time, CuePointType.Breakdown, "First Breakdown", brk1Cand.Time != 0 ? brk1Cand.Confidence : 0.6f));

        // Cue 5: Bridge / Second Breakdown
        var bridgeCand = candidates.FirstOrDefault(c => c.Intent == CueIntent.Bridge && c.Time > drop1Time);
        double bridgeTime = bridgeCand.Time != 0 ? bridgeCand.Time : drop1Time + (64 * beatDuration); // 16 bars after drop
        cues.Add(CreateCueEntity(trackHash, bridgeTime, CuePointType.Breakdown, "Second Breakdown", bridgeCand.Time != 0 ? bridgeCand.Confidence : 0.6f));

        // Cue 6: Second Drop
        var drop2Cand = candidates.FirstOrDefault(c => c.Intent == CueIntent.FirstDrop && c.Time > bridgeTime);
        double drop2Time = drop2Cand.Time != 0 ? drop2Cand.Time : bridgeTime + (32 * beatDuration); // 8 bars after bridge
        cues.Add(CreateCueEntity(trackHash, drop2Time, CuePointType.Drop, "Second Drop", drop2Cand.Time != 0 ? drop2Cand.Confidence : 0.7f));

        // Cue 7: Mix-Out Warning
        var mixOutCand = candidates.LastOrDefault(c => c.Intent == CueIntent.MixOutWarning);
        double mixOutTime = mixOutCand.Time != 0 ? mixOutCand.Time : duration - (64 * beatDuration); // 16 bars before end
        if (mixOutTime <= drop2Time) mixOutTime = duration - (32 * beatDuration);
        cues.Add(CreateCueEntity(trackHash, mixOutTime, CuePointType.Outro, "Mix-Out Warning", mixOutCand.Time != 0 ? mixOutCand.Confidence : 0.7f));

        // Cue 8: Final Beat
        double finalBeatTime = duration - beatDuration;
        if (analysis.Transients.Count > 0)
        {
            var lastTransient = analysis.Transients.Last();
            if (duration - lastTransient.Timestamp < 10.0)
            {
                finalBeatTime = lastTransient.Timestamp;
            }
        }
        cues.Add(CreateCueEntity(trackHash, finalBeatTime, CuePointType.Outro, "Final Beat", 1.0f));

        // Sort by timestamp ascending
        cues.Sort((a, b) => a.TimestampInSeconds.CompareTo(b.TimestampInSeconds));
        return cues;
    }

    private static CuePointEntity CreateCueEntity(
        string trackHash,
        double timestamp,
        CuePointType type,
        string label,
        float confidence)
    {
        string color = type switch
        {
            CuePointType.Intro => "#00FFFF",          // Cyan
            CuePointType.Outro => "#00FFFF",          // Cyan
            CuePointType.Drop => "#FF0000",           // Red
            CuePointType.Breakdown => "#800080",      // Purple
            CuePointType.Build => "#FFFF00",          // Yellow
            CuePointType.PhraseBoundary => "#0000FF", // Blue
            _ => "#FFFFFF"
        };

        return new CuePointEntity
        {
            Id = Guid.NewGuid(),
            TrackUniqueHash = trackHash,
            TimestampInSeconds = Math.Max(0.0, timestamp),
            Type = type,
            Label = label,
            Color = color,
            IsAutoGenerated = true,
            Confidence = Math.Clamp(confidence, 0f, 1f),
            CreatedAt = DateTime.UtcNow
        };
    }
}
