using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using SLSKDONET.Data;
using SLSKDONET.Data.Entities;
using SLSKDONET.Engine.Analysis;
using SLSKDONET.Engine.Snapping;
using SLSKDONET.Models;

namespace SLSKDONET.Engine.Cueing;

/// <summary>
/// Generates and persists the 8 standard structural DJ cues for a track.
///
/// Priority system:
///   1. EDMFormer phrase segments (ML-grade, from local microservice)  — best accuracy
///   2. Sub-bass return + spectral flux novelty signatures             — DSP-grade
///   3. Heuristic transient clustering with IntentClassifier           — fallback
///
/// Slot map (always 8 cues):
///   #1 First Downbeat (Intro)
///   #2 First Build / Mix-In
///   #3 First Breakdown
///   #4 First Drop
///   #5 Second Breakdown / Bridge
///   #6 Second Drop
///   #7 Mix-Out Warning
///   #8 Outro / Final Beat
/// </summary>
public sealed class CueGenerationService
{
    private readonly IDbContextFactory<AppDbContext> _contextFactory;
    private readonly TransientAwareSnappingEngine _snappingEngine;
    private readonly IntentClassifier _classifier;

    public CueGenerationService(IDbContextFactory<AppDbContext> contextFactory)
    {
        _contextFactory = contextFactory ?? throw new ArgumentNullException(nameof(contextFactory));
        _snappingEngine = new TransientAwareSnappingEngine();
        _classifier = new IntentClassifier();
    }

    // ── Public API ──────────────────────────────────────────────────────────

    public async Task<List<CuePointEntity>> GenerateAndPersistCuesAsync(
        string trackHash,
        AnalysisPipelineResult analysis,
        double downbeatAnchor,
        double? vocalStart = null,
        double? vocalEnd = null,
        double? vocalIntensity = null,
        CancellationToken ct = default)
    {
        var cues = GenerateCues(trackHash, analysis, downbeatAnchor, vocalStart, vocalEnd, vocalIntensity);

        using var db = await _contextFactory.CreateDbContextAsync(ct);
        var existing = await db.CuePoints
            .Where(c => c.TrackUniqueHash == trackHash && c.IsAutoGenerated)
            .ToListAsync(ct);

        db.CuePoints.RemoveRange(existing);
        await db.CuePoints.AddRangeAsync(cues, ct);
        await db.SaveChangesAsync(ct);
        return cues;
    }

    public List<CuePointEntity> GenerateCues(
        string trackHash,
        AnalysisPipelineResult analysis,
        double downbeatAnchor,
        double? vocalStart = null,
        double? vocalEnd = null,
        double? vocalIntensity = null)
    {
        double duration = analysis.DurationSeconds;
        double bpm = analysis.Bpm;
        if (duration <= 0 || bpm <= 0) return new List<CuePointEntity>();

        // ── Path 1: EDMFormer ML phrase segments ───────────────────────────
        if (analysis.PhraseSegments is { Count: >= 2 })
        {
            return GenerateCuesFromPhraseSegments(
                trackHash, analysis.PhraseSegments, duration, bpm, downbeatAnchor);
        }

        // ── Path 2: Heuristic DSP (unchanged original logic) ───────────────
        return GenerateCuesHeuristic(
            trackHash, analysis, downbeatAnchor, duration, bpm, vocalStart, vocalEnd, vocalIntensity);
    }

    // ── ML Path: phrase-segment-driven cue placement ────────────────────────

    private List<CuePointEntity> GenerateCuesFromPhraseSegments(
        string trackHash,
        IReadOnlyList<PhraseSegment> segments,
        double duration,
        double bpm,
        double downbeatAnchor)
    {
        var cues = new List<CuePointEntity>(8);
        double bar = 60.0 / bpm * 4;

        // Collect typed segment starts (ML confidence = 0.9 from EdmFormerService)
        var intros     = segments.Where(s => Is(s, "Intro")).ToList();
        var builds     = segments.Where(s => Is(s, "Build")).ToList();
        var drops      = segments.Where(s => Is(s, "Drop")).OrderBy(s => s.Start).ToList();
        var breakdowns = segments.Where(s => Is(s, "Breakdown")).OrderBy(s => s.Start).ToList();
        var outros     = segments.Where(s => Is(s, "Outro")).ToList();

        // #1 First Downbeat / Intro
        double introTime = intros.Count > 0
            ? SnapToBar(intros[0].Start, bpm, downbeatAnchor)
            : downbeatAnchor;
        cues.Add(Make(trackHash, introTime, CuePointType.Intro, "Intro", 1.0f));

        // #4 First Drop (anchor — everything else relative to this)
        double drop1Time = drops.Count > 0
            ? SnapToBar(drops[0].Start, bpm, downbeatAnchor)
            : duration * 0.35;

        // #2 First Build (before first drop)
        double build1Time;
        var buildBefore1 = builds.Where(b => b.Start < drops.FirstOrDefault()?.Start).ToList();
        if (buildBefore1.Count > 0)
            build1Time = SnapToBar(buildBefore1.Last().Start, bpm, downbeatAnchor);
        else
            build1Time = SnapToBar(drop1Time - bar * 16, bpm, downbeatAnchor); // 4 bars before
        build1Time = Math.Max(introTime + bar, build1Time);
        cues.Add(Make(trackHash, build1Time, CuePointType.Build, "Build", 0.9f));

        // #3 First Breakdown (just before first drop, after build)
        double brk1Time;
        var brkBefore1 = breakdowns.Where(b => b.Start < drops.FirstOrDefault()?.Start).ToList();
        if (brkBefore1.Count > 0)
            brk1Time = SnapToBar(brkBefore1.Last().Start, bpm, downbeatAnchor);
        else
            brk1Time = SnapToBar(drop1Time - bar * 8, bpm, downbeatAnchor); // 2 bars before
        brk1Time = Math.Clamp(brk1Time, build1Time + bar, drop1Time - bar);
        cues.Add(Make(trackHash, brk1Time, CuePointType.Breakdown, "Breakdown", 0.88f));

        cues.Add(Make(trackHash, drop1Time, CuePointType.Drop, "Drop 1", 0.95f));

        // #5 Second Breakdown / Bridge (after first drop)
        double brk2Time;
        var brkAfter1 = breakdowns.Where(b => b.Start > drop1Time).ToList();
        if (brkAfter1.Count > 0)
            brk2Time = SnapToBar(brkAfter1[0].Start, bpm, downbeatAnchor);
        else
            brk2Time = SnapToBar(drop1Time + bar * 16, bpm, downbeatAnchor);
        brk2Time = Math.Min(brk2Time, duration - bar * 4);
        cues.Add(Make(trackHash, brk2Time, CuePointType.Breakdown, "Breakdown 2", 0.85f));

        // #6 Second Drop
        double drop2Time;
        if (drops.Count >= 2)
            drop2Time = SnapToBar(drops[1].Start, bpm, downbeatAnchor);
        else
            drop2Time = SnapToBar(brk2Time + bar * 8, bpm, downbeatAnchor);
        drop2Time = Math.Min(drop2Time, duration - bar * 8);
        cues.Add(Make(trackHash, drop2Time, CuePointType.Drop, drops.Count >= 2 ? "Drop 2" : "Drop (reprise)", 0.88f));

        // #7 Mix-Out Warning (16 bars before outro or end)
        double outroStart = outros.Count > 0 ? outros[0].Start : duration;
        double mixOutTime = SnapToBar(outroStart - bar * 16, bpm, downbeatAnchor);
        mixOutTime = Math.Max(mixOutTime, drop2Time + bar * 4);
        cues.Add(Make(trackHash, mixOutTime, CuePointType.Outro, "Mix-Out", 0.85f));

        // #8 Outro
        double outroTime = outros.Count > 0
            ? SnapToBar(outros[0].Start, bpm, downbeatAnchor)
            : SnapToBar(duration - bar * 8, bpm, downbeatAnchor);
        outroTime = Math.Max(outroTime, mixOutTime + bar);
        cues.Add(Make(trackHash, outroTime, CuePointType.Outro, "Outro", 0.9f));

        cues.Sort((a, b) => a.TimestampInSeconds.CompareTo(b.TimestampInSeconds));
        return cues;
    }

    // ── Heuristic Path (original logic, preserved) ──────────────────────────

    private List<CuePointEntity> GenerateCuesHeuristic(
        string trackHash,
        AnalysisPipelineResult analysis,
        double downbeatAnchor,
        double duration,
        double bpm,
        double? vocalStart,
        double? vocalEnd,
        double? vocalIntensity)
    {
        var cues = new List<CuePointEntity>();
        double beatDuration = 60.0 / bpm;
        double barDuration = beatDuration * 4;

        var rawCandidates = new HashSet<double>();

        foreach (var t in analysis.Transients)
        {
            double snapped = _snappingEngine.SnapRawTimeToPhraseLedger(t.Timestamp, bpm, downbeatAnchor);
            if (vocalStart.HasValue && vocalEnd.HasValue && vocalIntensity.HasValue && vocalIntensity.Value > 0.4
                && snapped >= vocalStart.Value && snapped <= vocalEnd.Value)
            {
                double relativeToPhrase = (snapped - downbeatAnchor) / (beatDuration * 32);
                if (Math.Abs(relativeToPhrase - Math.Round(relativeToPhrase)) > 0.05)
                    snapped = _snappingEngine.SnapRawTimeToPhraseLedger(snapped, bpm, downbeatAnchor);
            }
            rawCandidates.Add(snapped);
        }

        foreach (var r in analysis.SubBassReturnTimestamps)
            rawCandidates.Add(_snappingEngine.SnapRawTimeToPhraseLedger(r, bpm, downbeatAnchor));

        foreach (var (dropTs, _, _) in analysis.NoveltyDropSignatures)
            rawCandidates.Add(_snappingEngine.SnapRawTimeToPhraseLedger(dropTs, bpm, downbeatAnchor));

        var classified = _classifier.ClassifyAll(rawCandidates, duration, analysis);
        var candidates = classified
            .Select(c => (Time: c.Timestamp, Intent: c.Result.Intent, Confidence: c.Result.Confidence))
            .ToList();

        double downbeatTime = downbeatAnchor;
        cues.Add(Make(trackHash, downbeatTime, CuePointType.Intro, "First Downbeat", 1.0f));

        var mixInCand = candidates.FirstOrDefault(c => c.Intent == CueIntent.MixIn);
        double mixInTime = mixInCand.Time != 0 ? mixInCand.Time : downbeatAnchor + 32 * beatDuration;
        cues.Add(Make(trackHash, mixInTime, CuePointType.Intro, "Mix-In", mixInCand.Time != 0 ? mixInCand.Confidence : 0.7f));

        var drop1Cand = candidates.FirstOrDefault(c => c.Intent == CueIntent.FirstDrop);
        double drop1Time = drop1Cand.Time != 0 ? drop1Cand.Time : downbeatAnchor + 64 * beatDuration;
        cues.Add(Make(trackHash, drop1Time, CuePointType.Drop, "First Drop", drop1Cand.Time != 0 ? drop1Cand.Confidence : 0.7f));

        var brk1Cand = candidates.FirstOrDefault(c => c.Intent == CueIntent.FirstBreakdown && c.Time < drop1Time);
        double brk1Time = brk1Cand.Time != 0 ? brk1Cand.Time : drop1Time - 32 * beatDuration;
        if (brk1Time <= mixInTime) brk1Time = drop1Time - 16 * beatDuration;
        cues.Add(Make(trackHash, brk1Time, CuePointType.Breakdown, "First Breakdown", brk1Cand.Time != 0 ? brk1Cand.Confidence : 0.6f));

        var bridgeCand = candidates.FirstOrDefault(c => c.Intent == CueIntent.Bridge && c.Time > drop1Time);
        double bridgeTime = bridgeCand.Time != 0 ? bridgeCand.Time : drop1Time + 64 * beatDuration;
        cues.Add(Make(trackHash, bridgeTime, CuePointType.Breakdown, "Second Breakdown", bridgeCand.Time != 0 ? bridgeCand.Confidence : 0.6f));

        var drop2Cand = candidates.FirstOrDefault(c => c.Intent == CueIntent.FirstDrop && c.Time > bridgeTime);
        double drop2Time = drop2Cand.Time != 0 ? drop2Cand.Time : bridgeTime + 32 * beatDuration;
        cues.Add(Make(trackHash, drop2Time, CuePointType.Drop, "Second Drop", drop2Cand.Time != 0 ? drop2Cand.Confidence : 0.7f));

        var mixOutCand = candidates.LastOrDefault(c => c.Intent == CueIntent.MixOutWarning);
        double mixOutTime = mixOutCand.Time != 0 ? mixOutCand.Time : duration - 64 * beatDuration;
        if (mixOutTime <= drop2Time) mixOutTime = duration - 32 * beatDuration;
        cues.Add(Make(trackHash, mixOutTime, CuePointType.Outro, "Mix-Out Warning", mixOutCand.Time != 0 ? mixOutCand.Confidence : 0.7f));

        double finalBeatTime = duration - beatDuration;
        if (analysis.Transients.Count > 0)
        {
            var lastTransient = analysis.Transients.Last();
            if (duration - lastTransient.Timestamp < 10.0)
                finalBeatTime = lastTransient.Timestamp;
        }
        cues.Add(Make(trackHash, finalBeatTime, CuePointType.Outro, "Final Beat", 1.0f));

        cues.Sort((a, b) => a.TimestampInSeconds.CompareTo(b.TimestampInSeconds));
        return cues;
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private static bool Is(PhraseSegment seg, string label) =>
        string.Equals(seg.Label, label, StringComparison.OrdinalIgnoreCase);

    private static double SnapToBar(double t, double bpm, double anchor)
    {
        double bar = 60.0 / bpm * 4;
        double offset = t - anchor;
        return anchor + Math.Round(offset / bar) * bar;
    }

    private static CuePointEntity Make(string trackHash, double ts, CuePointType type, string label, float confidence)
    {
        string color = type switch
        {
            CuePointType.Intro          => "#00FFFF",
            CuePointType.Outro          => "#00FFFF",
            CuePointType.Drop           => "#FF0000",
            CuePointType.Breakdown      => "#800080",
            CuePointType.Build          => "#FFFF00",
            CuePointType.PhraseBoundary => "#0000FF",
            _                           => "#FFFFFF",
        };
        return new CuePointEntity
        {
            Id = Guid.NewGuid(),
            TrackUniqueHash = trackHash,
            TimestampInSeconds = Math.Max(0.0, ts),
            Type = type,
            Label = label,
            Color = color,
            IsAutoGenerated = true,
            Confidence = Math.Clamp(confidence, 0f, 1f),
            CreatedAt = DateTime.UtcNow,
        };
    }
}
