using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using SLSKDONET.Data.Entities;

namespace SLSKDONET.Services;

/// <summary>
/// Maps raw <see cref="StructuralAnalysisResult"/> data into <see cref="CuePointEntity"/>
/// objects and persists them via <see cref="ICuePointService"/>.
///
/// Color convention (standardised for DJ hardware):
///   Intro / Outro  → Cyan    #00FFFF
///   Build          → Yellow  #FFFF00
///   Drop           → Red     #FF0000
///   Breakdown      → Purple  #800080
///   Phrase Boundary→ Blue    #0000FF
/// </summary>
public sealed class CueGenerationService
{
    // ── default colors per type ────────────────────────────────────────────
    private static readonly Dictionary<CuePointType, string> DefaultColors = new()
    {
        [CuePointType.Intro]          = "#00FFFF",
        [CuePointType.Outro]          = "#00FFFF",
        [CuePointType.Build]          = "#FFFF00",
        [CuePointType.Drop]           = "#FF0000",
        [CuePointType.Breakdown]      = "#800080",
        [CuePointType.PhraseBoundary] = "#0000FF",
    };

    // ── phrase cue spacing ─────────────────────────────────────────────────
    /// <summary>
    /// A phrase-boundary cue is placed every N beats along the energy curve.
    /// 32 beats = 8 bars in 4/4 time.
    /// </summary>
    private const int PhraseCueEveryBeats = 32;

    /// <summary>
    /// Minimum gap (seconds) between a drop and the nearest phrase-boundary cue.
    /// Prevents overcrowding near detected drops.
    /// </summary>
    private const double MinDropProximitySeconds = 4.0;

    private readonly ICuePointService _cuePointService;
    private readonly ILogger<CueGenerationService> _logger;

    public CueGenerationService(ICuePointService cuePointService, ILogger<CueGenerationService> logger)
    {
        _cuePointService = cuePointService;
        _logger = logger;
    }

    /// <summary>
    /// Deletes existing auto-generated cue points for the track, then generates and persists a
    /// fresh set from the supplied analysis result.
    /// </summary>
    /// <param name="trackUniqueHash">Track identifier (content hash).</param>
    /// <param name="analysisResult">Structural analysis data from <see cref="StructuralAnalysisEngine"/>.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The ordered list of generated cue points (not yet persisted on failure).</returns>
    public async Task<IReadOnlyList<CuePointEntity>> GenerateDefaultCuesAsync(
        string trackUniqueHash,
        StructuralAnalysisResult analysisResult,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(trackUniqueHash))
            throw new ArgumentNullException(nameof(trackUniqueHash));

        ArgumentNullException.ThrowIfNull(analysisResult);

        // 1. Build the cue list
        var cues = BuildCuePoints(trackUniqueHash, analysisResult);

        // 2. Replace auto-generated cues in the database
        await _cuePointService.DeleteAutoGeneratedByTrackIdAsync(trackUniqueHash, cancellationToken);
        await _cuePointService.CreateManyAsync(cues, cancellationToken);

        _logger.LogInformation(
            "Generated {Count} cue points for track {Hash} (BPM={Bpm}, Duration={Dur:F1}s, Drops={DropCount})",
            cues.Count, trackUniqueHash, analysisResult.Bpm, analysisResult.DurationSeconds, analysisResult.Drops.Count);

        return cues;
    }

    // ── internal helpers ───────────────────────────────────────────────────

    private static List<CuePointEntity> BuildCuePoints(
        string trackUniqueHash,
        StructuralAnalysisResult result)
    {
        var cues = new List<CuePointEntity>();

        // A. Intro cue at 0.0 s (or first detected beat when available)
        double introTimestamp = result.BeatTimestamps.Count > 0 ? result.BeatTimestamps[0] : 0.0;
        cues.Add(MakeCue(trackUniqueHash, introTimestamp, CuePointType.Intro, "Intro", confidence: 1.0f));

        // B. Drop cues – highest confidence first, numbered Drop 1 / Drop 2 / …
        var dropTimestamps = new HashSet<double>();
        int dropNumber = 1;
        foreach (var (ts, conf) in result.Drops)
        {
            string label = result.Drops.Count == 1 ? "Drop" : $"Drop {dropNumber}";

            // Also add a Build cue 16 bars before the drop (when BPM is known)
            if (result.Bpm > 0)
            {
                double barDuration = 60.0 / result.Bpm * 4;
                double buildTimestamp = ts - barDuration * 16;
                if (buildTimestamp >= 0)
                {
                    cues.Add(MakeCue(trackUniqueHash, buildTimestamp, CuePointType.Build,
                        result.Drops.Count == 1 ? "Build" : $"Build {dropNumber}",
                        confidence: conf * 0.9f)); // slightly lower confidence than the drop itself
                }
            }

            cues.Add(MakeCue(trackUniqueHash, ts, CuePointType.Drop, label, confidence: conf));
            dropTimestamps.Add(ts);
            dropNumber++;
        }

        // C. Phrase-boundary cues every 32 beats, skipping timestamps near a drop
        if (result.Bpm > 0 && result.BeatTimestamps.Count > 0)
        {
            double beatInterval = 60.0 / result.Bpm;
            double phraseStep = beatInterval * PhraseCueEveryBeats;

            int phraseNumber = 1;
            for (double t = phraseStep; t < result.DurationSeconds - beatInterval; t += phraseStep)
            {
                bool nearDrop = dropTimestamps.Any(d => Math.Abs(d - t) < MinDropProximitySeconds);
                if (nearDrop) continue;

                cues.Add(MakeCue(trackUniqueHash, t, CuePointType.PhraseBoundary,
                    $"Phrase {phraseNumber++}", confidence: 0.75f));
            }
        }

        // D. Outro cue: final phrase boundary (or last 8 bars if BPM available)
        // Always add outro – it overrides any nearby phrase boundary cue.
        double outroTimestamp = result.DurationSeconds;
        if (result.Bpm > 0)
        {
            double barDuration = 60.0 / result.Bpm * 4;
            outroTimestamp = Math.Max(0, result.DurationSeconds - barDuration * 8);
        }

        // Remove any phrase-boundary cue that is too close to the outro position,
        // then add the outro itself.
        cues.RemoveAll(c => c.Type == CuePointType.PhraseBoundary &&
                            Math.Abs(c.TimestampInSeconds - outroTimestamp) < MinDropProximitySeconds);

        cues.Add(MakeCue(trackUniqueHash, outroTimestamp, CuePointType.Outro, "Outro", confidence: 0.9f));

        // Sort by timestamp ascending
        cues.Sort((a, b) => a.TimestampInSeconds.CompareTo(b.TimestampInSeconds));
        return cues;
    }

    private static CuePointEntity MakeCue(
        string trackUniqueHash,
        double timestamp,
        CuePointType type,
        string label,
        float confidence)
    {
        return new CuePointEntity
        {
            Id = Guid.NewGuid(),
            TrackUniqueHash = trackUniqueHash,
            TimestampInSeconds = Math.Max(0, timestamp),
            Type = type,
            Label = label,
            Color = DefaultColors.TryGetValue(type, out var color) ? color : "#FFFFFF",
            IsAutoGenerated = true,
            Confidence = Math.Clamp(confidence, 0f, 1f),
            CreatedAt = DateTime.UtcNow,
        };
    }
}
