using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using Xunit;
using SLSKDONET.Data.Entities;
using SLSKDONET.Services;

namespace SLSKDONET.Tests.Services;

/// <summary>
/// Unit tests for CueGenerationService – verifies correct cue point mapping from analysis data.
/// </summary>
public class CueGenerationServiceTests
{
    private readonly Mock<ICuePointService> _cuePointServiceMock;
    private readonly CueGenerationService _service;

    public CueGenerationServiceTests()
    {
        _cuePointServiceMock = new Mock<ICuePointService>();
        _service = new CueGenerationService(
            _cuePointServiceMock.Object,
            new NullLogger<CueGenerationService>());
    }

    // ── GenerateDefaultCuesAsync ──────────────────────────────────────────

    [Fact]
    public async Task GenerateDefaultCues_AlwaysIncludesIntroAndOutro()
    {
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 128f, durationSeconds: 240.0);

        var cues = await _service.GenerateDefaultCuesAsync("hash1", analysis);

        Assert.Contains(cues, c => c.Type == CuePointType.Intro);
        Assert.Contains(cues, c => c.Type == CuePointType.Outro);
    }

    [Fact]
    public async Task GenerateDefaultCues_IntroTimestampIsNonNegative()
    {
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 128f, durationSeconds: 240.0);

        var cues = await _service.GenerateDefaultCuesAsync("hash1", analysis);

        var intro = cues.First(c => c.Type == CuePointType.Intro);
        Assert.True(intro.TimestampInSeconds >= 0.0);
    }

    [Fact]
    public async Task GenerateDefaultCues_DropsHaveRedColor()
    {
        // Build analysis result with a detected drop
        float bpm = 128f;
        double duration = 240.0;
        var energy = Enumerable.Range(0, (int)duration).Select(i => i >= 60 ? 0.9f : 0.2f).ToList<float>();
        energy[64] = 1.0f;
        var analysis = StructuralAnalysisEngine.Analyze(bpm, duration, energy);

        var cues = await _service.GenerateDefaultCuesAsync("hash2", analysis);

        foreach (var drop in cues.Where(c => c.Type == CuePointType.Drop))
        {
            Assert.Equal("#FF0000", drop.Color);
        }
    }

    [Fact]
    public async Task GenerateDefaultCues_AllCuesHaveCorrectTrackHash()
    {
        const string hash = "track_abc";
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 120f, durationSeconds: 180.0);

        var cues = await _service.GenerateDefaultCuesAsync(hash, analysis);

        Assert.All(cues, c => Assert.Equal(hash, c.TrackUniqueHash));
    }

    [Fact]
    public async Task GenerateDefaultCues_AllCuesAreAutoGenerated()
    {
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 120f, durationSeconds: 180.0);

        var cues = await _service.GenerateDefaultCuesAsync("hash3", analysis);

        Assert.All(cues, c => Assert.True(c.IsAutoGenerated));
    }

    [Fact]
    public async Task GenerateDefaultCues_CuesAreSortedByTimestamp()
    {
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 128f, durationSeconds: 300.0);

        var cues = await _service.GenerateDefaultCuesAsync("hash4", analysis);

        for (int i = 1; i < cues.Count; i++)
        {
            Assert.True(cues[i].TimestampInSeconds >= cues[i - 1].TimestampInSeconds,
                $"Cue at index {i} (ts={cues[i].TimestampInSeconds}) is before index {i-1} (ts={cues[i-1].TimestampInSeconds})");
        }
    }

    [Fact]
    public async Task GenerateDefaultCues_CallsDeleteBeforeCreate()
    {
        var callOrder = new List<string>();
        _cuePointServiceMock
            .Setup(s => s.DeleteAutoGeneratedByTrackIdAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Callback<string, CancellationToken>((_, _) => callOrder.Add("Delete"))
            .Returns(Task.CompletedTask);
        _cuePointServiceMock
            .Setup(s => s.CreateManyAsync(It.IsAny<IEnumerable<CuePointEntity>>(), It.IsAny<CancellationToken>()))
            .Callback<IEnumerable<CuePointEntity>, CancellationToken>((_, _) => callOrder.Add("Create"))
            .Returns(Task.CompletedTask);

        var analysis = StructuralAnalysisEngine.Analyze(bpm: 120f, durationSeconds: 180.0);
        await _service.GenerateDefaultCuesAsync("hash5", analysis);

        Assert.Equal(new[] { "Delete", "Create" }, callOrder);
    }

    [Fact]
    public async Task GenerateDefaultCues_ColorMappings_AreCorrect()
    {
        // Build an analysis result with drops so we can test all color types
        float bpm = 128f;
        double duration = 300.0;
        var energy = Enumerable.Range(0, (int)duration).Select(i => i >= 60 ? 0.9f : 0.2f).ToList<float>();
        energy[64] = 1.0f;
        var analysis = StructuralAnalysisEngine.Analyze(bpm, duration, energy);

        var cues = await _service.GenerateDefaultCuesAsync("hash6", analysis);

        foreach (var cue in cues)
        {
            string expected = cue.Type switch
            {
                CuePointType.Intro          => "#00FFFF",
                CuePointType.Outro          => "#00FFFF",
                CuePointType.Build          => "#FFFF00",
                CuePointType.Drop           => "#FF0000",
                CuePointType.Breakdown      => "#800080",
                CuePointType.PhraseBoundary => "#0000FF",
                _ => cue.Color
            };
            Assert.Equal(expected, cue.Color);
        }
    }

    [Fact]
    public async Task GenerateDefaultCues_PhraseBoundaries_NotNearDrops()
    {
        // Verify phrase boundary cues are not placed too close to detected drops
        float bpm = 128f;
        double duration = 300.0;
        var energy = Enumerable.Range(0, (int)duration).Select(i => i >= 60 ? 0.9f : 0.2f).ToList<float>();
        energy[64] = 1.0f;
        var analysis = StructuralAnalysisEngine.Analyze(bpm, duration, energy);

        var cues = await _service.GenerateDefaultCuesAsync("hash7", analysis);

        var dropTimestamps = cues.Where(c => c.Type == CuePointType.Drop).Select(c => c.TimestampInSeconds).ToList();
        var phraseBoundaries = cues.Where(c => c.Type == CuePointType.PhraseBoundary).ToList();

        foreach (var phrase in phraseBoundaries)
        {
            foreach (var dropTs in dropTimestamps)
            {
                Assert.True(
                    Math.Abs(phrase.TimestampInSeconds - dropTs) >= 3.0,
                    $"Phrase cue at {phrase.TimestampInSeconds:F2}s is too close to drop at {dropTs:F2}s");
            }
        }
    }

    [Fact]
    public async Task GenerateDefaultCues_ThrowsOnNullHash()
    {
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 120f, durationSeconds: 180.0);

        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _service.GenerateDefaultCuesAsync(null!, analysis));
    }

    [Fact]
    public async Task GenerateDefaultCues_ThrowsOnNullAnalysisResult()
    {
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _service.GenerateDefaultCuesAsync("hash", null!));
    }

    [Fact]
    public async Task GenerateDefaultCues_ConfidenceValues_InValidRange()
    {
        var analysis = StructuralAnalysisEngine.Analyze(bpm: 128f, durationSeconds: 300.0);

        var cues = await _service.GenerateDefaultCuesAsync("hash8", analysis);

        Assert.All(cues, c => Assert.InRange(c.Confidence, 0f, 1f));
    }

    [Fact]
    public async Task GenerateDefaultCues_WithDrops_IncludesBuildCue()
    {
        // A drop at ~64 s should produce a build cue ~32 bars (≈ 15 s at 128 BPM) before it
        float bpm = 128f;
        double duration = 300.0;
        var energy = Enumerable.Range(0, (int)duration).Select(i => i >= 60 ? 0.9f : 0.2f).ToList<float>();
        energy[64] = 1.0f;
        var analysis = StructuralAnalysisEngine.Analyze(bpm, duration, energy);

        if (analysis.Drops.Count > 0)
        {
            var cues = await _service.GenerateDefaultCuesAsync("hash9", analysis);
            Assert.Contains(cues, c => c.Type == CuePointType.Build);
        }
    }
}
