using System;

namespace SLSKDONET.Models;

/// <summary>
/// Source of a cue point.
/// </summary>
public enum CueSource
{
    Auto,  // Generated by ML/Heuristics
    User   // Manually placed or adjusted by user
}

/// <summary>
/// Professional role/label for a cue point.
/// </summary>
public enum CueRole
{
    Intro,
    KickIn,
    Breakdown,
    Breakdown2,
    Drop,
    Climax,
    Vocals,
    Outro,
    Bridge,
    Build,
    PhraseStart,
    Custom
}

/// <summary>
/// Represents a surgical cue point for DJ preparation.
/// part of the Phase 10 Interactive Cue Ecosystem.
/// </summary>
public class OrbitCue
{
    /// <summary>
    /// Position in seconds.
    /// </summary>
    public double Timestamp { get; set; }

    /// <summary>
    /// Human-readable name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Hex color code for DJ hardware (e.g., #FF0000 for Red/Drop).
    /// </summary>
    public string Color { get; set; } = "#FFFFFF";

    /// <summary>
    /// Whether this was generated by ORBIT or placed by the user.
    /// User cues are NEVER overwritten by auto-analysis.
    /// </summary>
    public CueSource Source { get; set; } = CueSource.Auto;

    /// <summary>
    /// Confidence score (0.0 - 1.0) based on transient alignment.
    /// Low confidence cues are flagged for "Review" in the UI.
    /// </summary>
    public double Confidence { get; set; } = 1.0;

    /// <summary>
    /// The structural role of this cue.
    /// </summary>
    public CueRole Role { get; set; } = CueRole.Custom;
    
    /// <summary>
    /// Optional slot index for hardware mapping (Hot Cue 1-8).
    /// </summary>
    public int SlotIndex { get; set; }
}
